### ISSUE TITLE
It is impossible to reference an ftp session via a local tuple

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#10]
```
    LOCAL @ftp
    ftp -cd /tmp -session @ftp @host @username @password
```

This generates the following exception:
> Ublu:1:UbluInterpreter.Thread[main,5,main]:SEVERE:ublu.command.CmdFTP.ftp():Session tuple @ftp does not reference FTP.
I can't find a way to create an ftp session that doesn't depend on a nonexistent global tuple.

**Comment by jwoehr** [comment]
Yeah, that's true. The `ftp` command is old and hideous. `-to` got preempted to either

- point to the target file, or
- store the FTP session messages

That meant I needed another dashcommand tuple to receive the session instance. Thus  `-sessiontuple` was born and it both receives a new instance and also means return the session tuple to the command. 

Oops. It's entirely ridiculous.

I have to rewrite the command so that `-to` stores the session tuple and `--,-ftp` is used to provide an instanced tuple to the command. I'll try to do that tomorrow, I don't quite have time tonight.

My apologies, Taylor, for the inconvenience.

**Comment by jwoehr** [comment]
Are we going to cause trouble for ourselves if I change the syntax?

**Comment by Taywee** [comment]
Not on my end, maybe on yours.  I don't use the ftp command of ublu anywhere other than the current chkpprc monitor, and I can prepare for the change there if it's announced.

**Comment by jwoehr** [comment]
This should work now.

**Comment by jwoehr** [comment]
Did you ever try this out?

**Comment by jwoehr** [comment]
Works for Taylor
